# Site settings
title: Minimal Description Length
url: "https://insujeon.github.io"
baseurl: ""
description: >
    Minimal Description Length Blog Under Cosntruction

# My information
email: insuj3on@gmail.com
author: Insu Jeon
profile: check out
twitter_username: insuj3on
github_username: insujeon
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: insujeon
  shortname: insujeon
utterances:
  repo: insujeon/insujeon.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/insujeon/insujeon.github.io/blame/master/_wiki"
edit: "https://github.com/insujeon/insujeon.github.io/edit/master/_wiki"
issue: "https://github.com/insujeon/insujeon.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
